---
title: "Research"
subtitle: ""
editor: 
  markdown: 
    wrap: 72
---

# Work in progress

### Political overreach, state capacity and firm dynamics

Political overreach into bureaucracy is a routine occurrence in India.
How does this affect bureaucrat's ability and effectiveness? I
investigate the effects of political overreach on local state capacity
as well as on firm behaviour. Using the universe of bureaucratic
postings and transfers and biographical data on state level politicians,
I empirically document that politician's characteristics are associated
with unusual transfer patterns. Using an Instrumental Variable that
captures the shock to politicians willingness to overreach, I estimate
the effect of political overreach on firm's entry and investment
behaviour. The goal with this project is to generate quantitative
evidence of growth effects of distortions arising out of political
frictions.

### Monopsony in informal labor market

(with Simoni Jain, University of California Berkeley)

We investigate a unique feature of the informal labor markets in India
where, due to regulatory costs, most small firms hire workers through a
third party subcontractor. A priori the subcontractors can potentially
reduce the hiring search friction. However, as hiring costs for
subcontractors tend to be convex in these settings, providing them
enough incentives would be increasing hard for firms specially at an
early stage of growth. In other words, firms are prone to be held up by
subcontractor's lack of incentive even when it may be optimal for them
to hire more. We experimentally vary support to subcontractors to
manipulate their hiring cost and investigate its effect on both offered
wages and firm productivity. In this project, our aim is to shed light
on frictions experienced by small firms and their effect on the growth
trajectory.

### Police funding inequality and police performance in US

(with Mitch Downey, IIES, Stockholm University)

Police departments in USA draw majority of their funding from revenues
generated by local governments. This means that funding for local police
can be unequal within a metropolitan area among neighbouring cities.
What are the consequences of this arrangement for the allocation of
police officers, the quality of police representation in
majority-minority communities, and aggregate crime and officer-involved
violence? Using a shift share instrument, we estimate the effects of
increasing income inequality in MSA's with high-levels of fiscal
fragmentation (i.e., instances where the population is divided across
many different legally and fiscally independent cities), both relative
to increasing inequality when fragmentation is low, and relative to
highly fragmented MSA's that do not see increasing inequality.

# Publications

*Pullabhotla, Hemant K., Mustafa Zahid, Sam Heft-Neal, Vaibhav Rathi,
and Marshall Burke*. "Global biomass fires and infant mortality."
Proceedings of the National Academy of Sciences 120, no. 23 (2023):
e2218210120.
